const ItemType = {
    StrawberrySeed: "StrawberrySeed",
    CornSeed: "CornSeed",
    PotatoSeed: "PotatoSeed",
    CarrotSeed: "CarrotSeed",
    LettuceSeed: "LettuceSeed",
    EggplantSeed: "EggplantSeed",
    PumpkinSeed: "PumpkinSeed",
    RaddishSeed: "RaddishSeed",
    TomatoSeed: "TomatoSeed",
    WatermelonSeed: "WatermelonSeed",
    WheatSeed: "WheatSeed",
    StarFlowerSeed: "StarFlowerSeed",
    Eggplant: "Eggplant",
    Pumpkin: "Pumpkin",
    Raddish: "Raddish",
    Tomato: "Tomato",
    Watermelon: "Watermelon",
    Wheat: "Wheat",
    Strawberry: "Strawberry",
    Corn: "Corn",
    Potato: "Potato",
    Carrot: "Carrot",
    Lettuce: "Lettuce",
    StarFlower: "StarFlower",
    SeaShell: "SeaShell",
    Diamond: "Diamond",
    Emerald: "Emerald",
    Ruby: "Ruby",
    Apple: "Apple",
    Rock: "Rock",
    Feather: "Feather",
    Wood: "Wood",
    Clover: "Clover",
}

export default ItemType